spring.application.name=bookingTickets
server.port=8080
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
logging.level.org.springframework.web=INFO
spring.jackson.default-property-inclusion=non_null
